---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
  - repo: local #https://github.com/PyCQA/docformatter/pull/287
    hooks:
      - id: docformatter
        name: docformatter
        entry: docformatter
        additional_dependencies: [docformatter==1.7.5, tomli]
        language: python
        types: [python]
        args: [--config, ./pyproject.toml]
  - repo: 'https://github.com/astral-sh/ruff-pre-commit'
    rev: v0.7.2
    hooks:
      - id: ruff
        types_or: [python, toml]
      - id: ruff-format
        types_or: [python, toml]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
