# ruff rules: https://docs.astral.sh/ruff/rules/
# docformatter: https://docformatter.readthedocs.io/en/latest/usage.html#use-with-pre-commit

[tool.ruff]
fix=true
unsafe-fixes = true
line-length = 100
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = [
  "F",
  "E",
  "W",
  "I",
  "B",
  "C4",
  "D",
  "N",
  "BLE",
  "FBT",
  "A",
  "COM",
  "EM",
  "LOG",
  "G",
  "PIE",
  "T20",
  "Q",
  "PT",
  "RSE",
  "RET",
  "SLF",
  "SIM",
  "TID",
  "TCH",
  "ARG",
  "UP",
  "PL",
]
fixable = ["ALL"]
ignore = ["COM812", "PLR0912"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true # only formats code within docstrings

[tool.docformatter]
wrap-summaries = 100
wrap-descriptions = 100
in-place = true
blank = true
config = "./pyproject.toml"
