name: Compile LaTeX to PDF

on:
  push:
    paths:
      - 'thesis_document/jakub_dunaj_bachelors_thesis.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: jakub_dunaj_bachelors_thesis.tex
          working_directory: thesis_document

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: CompiledThesisPDF
          path: thesis_document/jakub_dunaj_bachelors_thesis.pdf
