---
name: comlipel-latex-to-pdf

on:
  push:
    paths:
      - 'thesis_document/jakub_dunaj_bachelors_thesis.tex'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: jakub_dunaj_bachelors_thesis.tex
          working_directory: thesis_document
      - uses: actions/upload-artifact@v4
        with:
          name: CompiledThesisPDF
          path: thesis_document/jakub_dunaj_bachelors_thesis.pdf
